# Generated by Django 5.0.4 on 2026-04-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('icon_class', models.CharField(default='fa-solid fa-code', help_text='Font Awesome class, e.g. fa-brands fa-python', max_length=120)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], db_index=True, max_length=8)),
                ('text', models.TextField()),
                ('choice_a', models.CharField(max_length=500)),
                ('choice_b', models.CharField(max_length=500)),
                ('choice_c', models.CharField(max_length=500)),
                ('choice_d', models.CharField(max_length=500)),
                ('correct', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.language')),
            ],
            options={
                'ordering': ['language', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], max_length=8)),
                ('score', models.PositiveSmallIntegerField()),
                ('total', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
